# Generated by Django 4.1 on 2022-08-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
                ('idade', models.IntegerField()),
                ('telefone', models.IntegerField(max_length=9)),
                ('bairro', models.CharField(max_length=124)),
                ('rua', models.CharField(max_length=124)),
                ('num_casa', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
                ('autor', models.CharField(max_length=124)),
                ('duracao', models.TimeField()),
                ('genero', models.TextField()),
                ('data_criacao', models.DateField()),
            ],
        ),
    ]
