# Generated by Django 4.1 on 2022-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cliente_options_alter_filme_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filme',
            options={},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='num_casa',
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.TextField(max_length=9),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('1', 'Terror'), ('2', 'Comédia'), ('3', 'LGBT')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('1', 'PENDENTE'), ('2', 'ENTREGUE'), ('3', 'DEVOLVIDO')], max_length=1),
        ),
    ]
