# Generated by Django 4.1 on 2022-09-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_filme_options_alter_cliente_num_casa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='id',
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_id',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='num_casa',
            field=models.TextField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.TextField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('Terror', 'Terror'), ('Comédia', 'Comédia'), ('Ação', 'Ação'), ('Romance', 'Romance'), ('Aventura', 'Aventura'), ('Suspense', 'Suspense'), ('Ficção Científica', 'Ficção Científica'), ('Drama', 'Drama'), ('Documentário', 'Documentário'), ('LGBTQ', 'LGBTQ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('ENTREGUE', 'ENTREGUE'), ('DEVOLVIDO', 'DEVOLVIDO')], max_length=20),
        ),
    ]
