# Generated by Django 4.1 on 2022-09-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_reserva_id_reserva_reserva_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='reserva_id',
        ),
        migrations.AddField(
            model_name='reserva',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
